### ISSUE TITLE
Test Suite Failures grape 2.1.0 + rack 3.1.3

### ISSUE THREAD

**Issue by arielvalentin** [open-telemetry/opentelemetry-ruby-contrib#1015]
https://github.com/open-telemetry/opentelemetry-ruby-contrib/actions/runs/9536427741/job/26283352331

```console
  LoadError: cannot load such file -- builder
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.16/lib/zeitwerk/kernel.rb:34:in `require'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/builder.rb:4:in `<top (required)>'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.16/lib/zeitwerk/kernel.rb:34:in `require'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/core_ext/hash/conversions.rb:75:in `to_xml'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/grape-2.1.0/lib/grape/error_formatter/xml.rb:16:in `call'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/grape-2.1.0/lib/grape/middleware/error.rb:49:in `format_message'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/grape-2.1.0/lib/grape/middleware/error.rb:74:in `error_response'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/grape-2.1.0/lib/grape/middleware/error.rb:34:in `call!'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/grape-2.1.0/lib/grape/middleware/base.rb:27:in `call'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/rack-3.1.3/lib/rack/head.rb:15:in `call'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/grape-2.1.0/lib/grape/endpoint.rb:225:in `call!'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/grape-2.1.0/lib/grape/endpoint.rb:219:in `call'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/grape-2.1.0/lib/grape/router/route.rb:19:in `exec'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/grape-2.1.0/lib/grape/router.rb:121:in `process_route'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/grape-2.1.0/lib/grape/router.rb:68:in `block in identity'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/grape-2.1.0/lib/grape/router.rb:101:in `transaction'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/grape-2.1.0/lib/grape/router.rb:66:in `identity'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/grape-2.1.0/lib/grape/router.rb:50:in `block in call'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/grape-2.1.0/lib/grape/router.rb:137:in `with_optimization'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/grape-2.1.0/lib/grape/router.rb:49:in `call'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/grape-2.1.0/lib/grape/api/instance.rb:164:in `call'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/grape-2.1.0/lib/grape/api/instance.rb:68:in `call!'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/grape-2.1.0/lib/grape/api/instance.rb:63:in `call'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/grape-2.1.0/lib/grape/api.rb:78:in `call'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/rack-3.1.3/lib/rack/events.rb:116:in `call'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/rack-3.1.3/lib/rack/mock_request.rb:76:in `request'
      /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/rack-3.1.3/lib/rack/mock_request.rb:49:in `get'
      test/opentelemetry/instrumentation/grape_test.rb:344:in `block (4 levels) in <top (required)>'
```

cc: @muripic

**Comment by arielvalentin** [comment]
Looks like `builder` was dropped as a dependency:

https://github.com/ruby-grape/grape/issues/2443
https://github.com/ruby-grape/grape/pull/2445
