### ISSUE TITLE
que test suite failures

### ISSUE THREAD

**Issue by arielvalentin** [open-telemetry/opentelemetry-ruby-contrib#1110]
The nightly build for queue started failing with what seems to be incompatibilities with newer versions of Rails.

cc: @indrekj as the current maintainer of the que instrumentation. 

```console
1) Error:
  OpenTelemetry::Instrumentation::Que::span propagation::when propagation_style is set to link#test_0003_links spans together:
  NoMethodError: undefined method `clear_active_connections!' for class ActiveRecord::Base
      /opt/hostedtoolcache/Ruby/3.3.4/x64/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
      /opt/hostedtoolcache/Ruby/3.3.4/x64/lib/ruby/gems/3.3.0/gems/que-1.4.0/lib/que/active_record/connection.rb:45:in `call'
      /opt/hostedtoolcache/Ruby/3.3.4/x64/lib/ruby/gems/3.3.0/gems/que-1.4.0/lib/que/utils/middleware.rb:36:in `invoke_middleware'
      (eval at /opt/hostedtoolcache/Ruby/3.3.4/x64/lib/ruby/gems/3.3.0/gems/que-1.4.0/lib/que/utils/middleware.rb:14):11:in `run_job_middleware'
      test/opentelemetry/instrumentation/que_test.rb:[170](https://github.com/open-telemetry/opentelemetry-ruby-contrib/actions/runs/10335505991/job/28610140236#step:4:181):in `block (4 levels) in <top (required)>'
```

https://github.com/open-telemetry/opentelemetry-ruby-contrib/actions/runs/10335505991/job/28610140236

**Comment by kaylareopelle** [comment]
This is temporarily fixed by #1112, by preventing the tests from running on 7.2. 

https://github.com/que-rb/que/pull/423 at commit [dcdbe94](https://github.com/que-rb/que/pull/423/commits/dcdbe9466c019d68b21a85cac2d6e01f63521f58) will get the tests to pass with Rails 7.2. However, it's still in review. Further discussion in https://github.com/que-rb/que/issues/425.

**Comment by kaylareopelle** [comment]
Reached back out on https://github.com/que-rb/que/issues/425 to check the status.

**Comment by kaylareopelle** [comment]
The PR to support Rails 7.2 hasn't been merged yet. I'll use the stalebot's cycle to remind me to check the status.

**Comment by kaylareopelle** [comment]
PR to fix this ready for review: https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/1256
