### ISSUE TITLE
Exception during during install of OpenTelemetry::Instrumentation::ActiveRecord

### ISSUE THREAD

**Issue by fcbr** [open-telemetry/opentelemetry-ruby-contrib#1124]
**Description of the bug**

We are getting the following exception when booting up a Rails application:

```
E, [2024-08-19T11:08:47.064333 #45] ERROR -- : OpenTelemetry error: Instrumentation: OpenTelemetry::Instrumentation::ActiveRecord unhandled exception during install: ["/app/vendor/bundle/ruby/3.3.0/gems/opentelemetry-instrumentation-active_record-0.7.3/lib/opentelemetry/instrumentation/active_record/instrumentation.rb:45:in `patch_activerecord'", "/app/vendor/bundle/ruby/3.3.0/gems/opentelemetry-instrumentation-active_record-0.7.3/lib/opentelemetry/instrumentation/active_record/instrumentation.rb:16:in `block in <class:Instrumentation>'", "/app/vendor/bundle/ruby/3.3.0/gems/opentelemetry-instrumentation-base-0.22.6/lib/opentelemetry/instrumentation/base.rb:222:in `instance_exec'", "/app/vendor/bundle/ruby/3.3.0/gems/opentelemetry-instrumentation-base-0.22.6/lib/opentelemetry/instrumentation/base.rb:222:in `install'", "/app/vendor/bundle/ruby/3.3.0/gems/opentelemetry-registry-0.3.1/lib/opentelemetry/instrumentation/registry.rb:80:in `install_instrumentation'", "/app/vendor/bundle/ruby/3.3.0/gems/opentelemetry-registry-0.3.1/lib/opentelemetry/instrumentation/registry.rb:51:in `block (2 levels) in install'", "/app/vendor/bundle/ruby/3.3.0/gems/opentelemetry-registry-0.3.1/lib/opentelemetry/instrumentation/registry.rb:46:in `each'", "/app/vendor/bundle/ruby/3.3.0/gems/opentelemetry-registry-0.3.1/lib/opentelemetry/instrumentation/registry.rb:46:in `block in install'", "/app/vendor/bundle/ruby/3.3.0/gems/opentelemetry-registry-0.3.1/lib/opentelemetry/instrumentation/registry.rb:45:in `synchronize'", "/app/vendor/bundle/ruby/3.3.0/gems/opentelemetry-registry-0.3.1/lib/opentelemetry/instrumentation/registry.rb:45:in `install'", "/app/vendor/bundle/ruby/3.3.0/gems/opentelemetry-sdk-1.5.0/lib/opentelemetry/sdk/configurator.rb:164:in `install_instrumentation'", "/app/vendor/bundle/ruby/3.3.0/gems/opentelemetry-sdk-1.5.0/lib/opentelemetry/sdk/configurator.rb:145:in `configure'", "/app/vendor/bundle/ruby/3.3.0/gems/opentelemetry-sdk-1.5.0/lib/opentelemetry/sdk.rb:66:in `configure'", "/app/config/initializers/opentelemetry.rb:8:in `<top (required)>'", "/app/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/engine.rb:690:in `load'", "/app/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/engine.rb:690:in `block in load_config_initializer'", "/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/notifications.rb:208:in `instrument'", "/app/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/engine.rb:689:in `load_config_initializer'", "/app/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/engine.rb:643:in `block (2 levels) in <class:Engine>'", "/app/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/engine.rb:642:in `each'", "/app/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/engine.rb:642:in `block in <class:Engine>'", "/app/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/initializable.rb:32:in `instance_exec'", "/app/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/initializable.rb:32:in `run'", "/app/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/initializable.rb:61:in `block in run_initializers'", "/usr/local/lib/ruby/3.3.0/tsort.rb:231:in `block in tsort_each'", "/usr/local/lib/ruby/3.3.0/tsort.rb:353:in `block (2 levels) in each_strongly_connected_component'", "/usr/local/lib/ruby/3.3.0/tsort.rb:425:in `block (2 levels) in each_strongly_connected_component_from'", "/usr/local/lib/ruby/3.3.0/tsort.rb:434:in `each_strongly_connected_component_from'", "/usr/local/lib/ruby/3.3.0/tsort.rb:424:in `block in each_strongly_connected_component_from'", "/app/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/initializable.rb:50:in `each'", "/app/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/initializable.rb:50:in `tsort_each_child'", "/usr/local/lib/ruby/3.3.0/tsort.rb:418:in `call'", "/usr/local/lib/ruby/3.3.0/tsort.rb:418:in `each_strongly_connected_component_from'", "/usr/local/lib/ruby/3.3.0/tsort.rb:352:in `block in each_strongly_connected_component'", "/usr/local/lib/ruby/3.3.0/tsort.rb:350:in `each'", "/usr/local/lib/ruby/3.3.0/tsort.rb:350:in `call'", "/usr/local/lib/ruby/3.3.0/tsort.rb:350:in `each_strongly_connected_component'", "/usr/local/lib/ruby/3.3.0/tsort.rb:229:in `tsort_each'", "/usr/local/lib/ruby/3.3.0/tsort.rb:208:in `tsort_each'", "/app/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/initializable.rb:60:in `run_initializers'", "/app/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/application.rb:426:in `initialize!'", "/app/config/environment.rb:5:in `<top (required)>'", "/usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'", "/usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'", "/app/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.6.17/lib/zeitwerk/kernel.rb:34:in `require'", "/app/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/application.rb:402:in `require_environment!'", "/app/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/command/actions.rb:20:in `boot_application!'", "/app/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/commands/console/console_command.rb:105:in `perform'", "/app/vendor/bundle/ruby/3.3.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'", "/app/vendor/bundle/ruby/3.3.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'", "/app/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/command/base.rb:178:in `invoke_command'", "/app/vendor/bundle/ruby/3.3.0/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'", "/app/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/command/base.rb:73:in `perform'", "/app/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/command.rb:71:in `block in invoke'", "/app/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/command.rb:149:in `with_argv'", "/app/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/command.rb:69:in `invoke'", "/app/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.4/lib/rails/commands.rb:18:in `<top (required)>'", "/usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'", "/usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'", "/app/bin/rails:4:in `<main>'"] - undefined method `on_load' for module OpenTelemetry::Instrumentation::ActiveSupport
```

I posted the entire exception for context, but the relevant fragment is this one at the end:

```
undefined method `on_load' for module OpenTelemetry::Instrumentation::ActiveSupport
```

**Share details about your runtime**

Operating system details: Debian 11 Slim "Bullseye"
RUBY_ENGINE: "ruby"
RUBY_VERSION: "3.3.4"
RUBY_DESCRIPTION: "ruby 3.3.4 (2024-07-09 revision be1089c8ec) [x86_64-linux]"

**Share a simplified reproduction if possible**

It's hard to give a standalone repro but I think the issue is the scoping of `ActiveSupport.on_load` [here](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/efaa4040b6e84989efd241d0f988276c83c7a762/instrumentation/active_record/lib/opentelemetry/instrumentation/active_record/instrumentation.rb#L45-L57). Shouldn't it be `::ActiveSupport`?

**Comment by arielvalentin** [comment]
Cc: @bensheldon

**Comment by arielvalentin** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/1123

**Comment by arielvalentin** [comment]
Thank you for reporting this issue. The latest release should contain a fix for this issue:

https://github.com/open-telemetry/opentelemetry-ruby-contrib/releases/tag/opentelemetry-instrumentation-active_record%2Fv0.7.4
