### ISSUE TITLE
DelayedJob Rails 8.0 Compatibility Error: `uninitialized constant ActiveSupport::BasicObject (NameError)`

### ISSUE THREAD

**Issue by arielvalentin** [open-telemetry/opentelemetry-ruby-contrib#1236]
`DelayedJob` seems to be incompatible with Rails 8 causing our canary tests to fail. 

```console
/opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/delayed_job-2.0.6/lib/delayed/message_sending.rb:2:in `<module:Delayed>': uninitialized constant ActiveSupport::BasicObject (NameError)

  class DelayProxy < ActiveSupport::BasicObject
                                  ^^^^^^^^^^^^^
Did you mean?  BasicSocket
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/delayed_job-2.0.6/lib/delayed/message_sending.rb:1:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/delayed_job-2.0.6/lib/delayed_job.rb:3:in `<top (required)>'
	from <internal:/opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/3.3.0/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/3.3.0/bundler/runtime.rb:55:in `each'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/3.3.0/bundler/runtime.rb:55:in `block in require'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/3.3.0/bundler/runtime.rb:44:in `each'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/3.3.0/bundler/runtime.rb:44:in `require'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/3.3.0/bundler.rb:212:in `require'
	from /home/runner/work/opentelemetry-ruby-contrib/opentelemetry-ruby-contrib/releases/test/test_helper.rb:8:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
	from /home/runner/work/opentelemetry-ruby-contrib/opentelemetry-ruby-contrib/releases/test/integration/installation_test.rb:7:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
	from -e:1:in `<main>'
rake aborted!
Command failed with status (1): [/opt/hostedtoolcache/Ruby/3.3.5/x64/bin/ruby -Ilib:test:.:test:lib -e 'require "minitest/autorun"; require "test/integration/installation_test.rb"' -- ]
/opt/hostedtoolcache/Ruby/3.3.5/x64/bin/bundle:25:in `load'
/opt/hostedtoolcache/Ruby/3.3.5/x64/bin/bundle:25:in `<main>'
```

https://github.com/open-telemetry/opentelemetry-ruby-contrib/actions/runs/11743544247/job/32716636494

**Comment by kaylareopelle** [comment]
Thanks for opening this issue, @arielvalentin! This PR on the DelayedJob repo might fix the problem: https://github.com/collectiveidea/delayed_job/pull/1219

**Comment by arielvalentin** [comment]
I think we need to add more appraisals and pin specific supported rails versions. 

Hopefully once a compatible version is released we can update the appraisals to test against rails latest.

**Comment by arielvalentin** [comment]
@kaylareopelle 4.1.13 was released with Rails 8 support. https://github.com/collectiveidea/delayed_job/blob/v4.1.13/CHANGELOG.md#4113---2024-11-08 

I am going to close this issue and open a PR to update the matrices.
