### ISSUE TITLE
ActionPack Instrumentation Fails to Install on Rails 7.x

### ISSUE THREAD

**Issue by paychex-ssmithrand** [open-telemetry/opentelemetry-ruby-contrib#393]
When using ActionPack instrumentation on a 7.x Rails application, the Instrumentation fails to install due to "cannot modify frozen array" error. I'm guessing the middlewares array gets frozen prior to ActionPack being added to the array.

```
E,
 [2023-03-22T16:26:44.130316 #73382] ERROR -- : OpenTelemetry error: Instrumentation: OpenTelemetry::Instrumentation::ActionPack unhandled exception during install: ["/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/stack.rb:102:in `insert'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/actionpack-7.0.4.3/lib/action_dispatch/middleware/stack.rb:102:in `insert'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/opentelemetry-instrumentation-action_pack-0.3.0/lib/opentelemetry/instrumentation/action_pack/railtie.rb:15:in `block in <class:Railtie>'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/activesupport-7.0.4.3/lib/active_support/lazy_load_hooks.rb:92:in `block in execute_hook'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/activesupport-7.0.4.3/lib/active_support/lazy_load_hooks.rb:85:in `with_execution_control'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/activesupport-7.0.4.3/lib/active_support/lazy_load_hooks.rb:90:in `execute_hook'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/activesupport-7.0.4.3/lib/active_support/lazy_load_hooks.rb:60:in `block in on_load'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/activesupport-7.0.4.3/lib/active_support/lazy_load_hooks.rb:59:in `each'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/activesupport-7.0.4.3/lib/active_support/lazy_load_hooks.rb:59:in `on_load'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/railties-7.0.4.3/lib/rails/railtie/configuration.rb:66:in `before_initialize'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/opentelemetry-instrumentation-action_pack-0.3.0/lib/opentelemetry/instrumentation/action_pack/railtie.rb:12:in `<class:Railtie>'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/opentelemetry-instrumentation-action_pack-0.3.0/lib/opentelemetry/instrumentation/action_pack/railtie.rb:11:in `<module:ActionPack>'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/opentelemetry-instrumentation-action_pack-0.3.0/lib/opentelemetry/instrumentation/action_pack/railtie.rb:9:in `<module:Instrumentation>'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/opentelemetry-instrumentation-action_pack-0.3.0/lib/opentelemetry/instrumentation/action_pack/railtie.rb:8:in `<module:OpenTelemetry>'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/opentelemetry-instrumentation-action_pack-0.3.0/lib/opentelemetry/instrumentation/action_pack/railtie.rb:7:in `<top (required)>'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/zeitwerk-2.6.1/lib/zeitwerk/kernel.rb:35:in `require'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/zeitwerk-2.6.1/lib/zeitwerk/kernel.rb:35:in `require'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/dead_end-4.0.0/lib/dead_end/core_ext.rb:82:in `require_relative'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/opentelemetry-instrumentation-action_pack-0.3.0/lib/opentelemetry/instrumentation/action_pack/instrumentation.rb:45:in `require_railtie'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/opentelemetry-instrumentation-action_pack-0.3.0/lib/opentelemetry/instrumentation/action_pack/instrumentation.rb:15:in `block in <class:Instrumentation>'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/opentelemetry-instrumentation-base-0.21.1/lib/opentelemetry/instrumentation/base.rb:221:in `instance_exec'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/opentelemetry-instrumentation-base-0.21.1/lib/opentelemetry/instrumentation/base.rb:221:in `install'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/opentelemetry-registry-0.2.0/lib/opentelemetry/instrumentation/registry.rb:78:in `install_instrumentation'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/opentelemetry-registry-0.2.0/lib/opentelemetry/instrumentation/registry.rb:51:in `block (2 levels) in install'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/opentelemetry-registry-0.2.0/lib/opentelemetry/instrumentation/registry.rb:46:in `each'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/opentelemetry-registry-0.2.0/lib/opentelemetry/instrumentation/registry.rb:46:in `block in install'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/opentelemetry-registry-0.2.0/lib/opentelemetry/instrumentation/registry.rb:45:in `synchronize'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/opentelemetry-registry-0.2.0/lib/opentelemetry/instrumentation/registry.rb:45:in `install'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/opentelemetry-sdk-1.2.0/lib/opentelemetry/sdk/configurator.rb:164:in `install_instrumentation'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/opentelemetry-sdk-1.2.0/lib/opentelemetry/sdk/configurator.rb:145:in `configure'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/opentelemetry-sdk-1.2.0/lib/opentelemetry/sdk.rb:66:in `configure'",
 "/home/ssmithra/code/flock-integrate/config/initializers/01_opentelemetry.rb:12:in `block in <top (required)>'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:445:in `instance_exec'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:445:in `block in make_lambda'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:199:in `block (2 levels) in halting'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:687:in `block (2 levels) in default_terminator'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:686:in `catch'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:686:in `block in default_terminator'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:200:in `block in halting'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:595:in `block in invoke_before'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:595:in `each'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:595:in `invoke_before'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:106:in `run_callbacks'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/activesupport-7.0.4.3/lib/active_support/reloader.rb:88:in `prepare!'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/railties-7.0.4.3/lib/rails/application/finisher.rb:68:in `block in <module:Finisher>'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/railties-7.0.4.3/lib/rails/initializable.rb:32:in `instance_exec'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/railties-7.0.4.3/lib/rails/initializable.rb:32:in `run'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/railties-7.0.4.3/lib/rails/initializable.rb:61:in `block in run_initializers'",
 "/home/ssmithra/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'",
 "/home/ssmithra/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'",
 "/home/ssmithra/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'",
 "/home/ssmithra/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'",
 "/home/ssmithra/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `each'",
 "/home/ssmithra/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `call'",
 "/home/ssmithra/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'",
 "/home/ssmithra/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'",
 "/home/ssmithra/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/railties-7.0.4.3/lib/rails/initializable.rb:60:in `run_initializers'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/railties-7.0.4.3/lib/rails/application.rb:372:in `initialize!'",
 "/home/ssmithra/code/flock-integrate/config/environment.rb:5:in `<top (required)>'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/zeitwerk-2.6.1/lib/zeitwerk/kernel.rb:35:in `require'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/zeitwerk-2.6.1/lib/zeitwerk/kernel.rb:35:in `require'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/dead_end-4.0.0/lib/dead_end/core_ext.rb:71:in `require'",
 "config.ru:8:in `block in <main>'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/rack-2.2.4/lib/rack/builder.rb:116:in `eval'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/rack-2.2.4/lib/rack/builder.rb:116:in `new_from_string'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/rack-2.2.4/lib/rack/builder.rb:105:in `load_file'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/rack-2.2.4/lib/rack/builder.rb:66:in `parse_file'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/rack-2.2.4/lib/rack/server.rb:349:in `build_app_and_options_from_config'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/rack-2.2.4/lib/rack/server.rb:249:in `app'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/rack-2.2.4/lib/rack/server.rb:422:in `wrapped_app'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/railties-7.0.4.3/lib/rails/commands/server/server_command.rb:76:in `log_to_stdout'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/railties-7.0.4.3/lib/rails/commands/server/server_command.rb:36:in `start'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/railties-7.0.4.3/lib/rails/commands/server/server_command.rb:143:in `block in perform'",
 "<internal:kernel>:90:in `tap'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/railties-7.0.4.3/lib/rails/commands/server/server_command.rb:134:in `perform'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/railties-7.0.4.3/lib/rails/command/base.rb:87:in `perform'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/railties-7.0.4.3/lib/rails/command.rb:48:in `invoke'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/railties-7.0.4.3/lib/rails/commands.rb:18:in `<top (required)>'",
 "/home/ssmithra/code/flock-integrate/bin/rails:9:in `require'",
 "/home/ssmithra/code/flock-integrate/bin/rails:9:in `<top (required)>'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/spring-4.1.0/lib/spring/client/rails.rb:28:in `load'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/spring-4.1.0/lib/spring/client/rails.rb:28:in `call'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/spring-4.1.0/lib/spring/client/command.rb:7:in `call'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/spring-4.1.0/lib/spring/client.rb:30:in `run'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/spring-4.1.0/bin/spring:49:in `<top (required)>'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/spring-4.1.0/lib/spring/binstub.rb:11:in `load'",
 "/home/ssmithra/.rvm/gems/ruby-3.1.2@flock_7_new/gems/spring-4.1.0/lib/spring/binstub.rb:11:in `<top (required)>'",
 "/home/ssmithra/code/flock-integrate/bin/spring:16:in `require'",
 "/home/ssmithra/code/flock-integrate/bin/spring:16:in `<top (required)>'",
 "bin/rails:3:in `load'",
 "bin/rails:3:in `<main>'"] - can't modify frozen Array: [Rack::MiniProfiler,
 Rack::Cors,
 ActionDispatch::HostAuthorization,
 Rack::Sendfile,
 ActionDispatch::Static,
 ActionDispatch::Executor,
 ActiveSupport::Cache::Strategy::LocalCache::Middleware,
 Rack::Timeout,
 Rack::Runtime,
 Rack::MethodOverride,
 ActionDispatch::RequestId,
 RequestStore::Middleware,
 ActionDispatch::RemoteIp,
 Sprockets::Rails::QuietAssets,
 Rails::Rack::Logger,
 ActionDispatch::ShowExceptions,
 ActionDispatch::DebugExceptions,
 BetterErrors::Middleware,
 Appsignal::Rack::RailsInstrumentation,
 ActionDispatch::ActionableExceptions,
 ActionDispatch::Reloader,
 ActionDispatch::Callbacks,
 ActiveRecord::Migration::CheckPending,
 ActionDispatch::Cookies,
 ActionDispatch::Session::CookieStore,
 ActionDispatch::Flash,
 ActionDispatch::ContentSecurityPolicy::Middleware,
 ActionDispatch::PermissionsPolicy::Middleware,
 Rack::Head,
 Rack::ConditionalGet,
 Rack::ETag,
 Rack::TempfileReaper,
 ActiveRecord::Middleware::DatabaseSelector,
 Warden::Manager,
 Bullet::Rack,
 OmniAuth::Strategies::GoogleOauth2]
```

**Comment by paychex-ssmithrand** [comment]
Closing this issue. Cause was the OpenTelemetry SDK Configuration was happening inside a `Rails.application.config.to_prepare` block and the array to update would already be frozen by then.
