### ISSUE TITLE
ArgumentError `GraphqlController#execute` wrong number of arguments (given 1, expected 0; required keyword: field) (ArgumentError)

### ISSUE THREAD

**Issue by dorianmariefr** [open-telemetry/opentelemetry-ruby-contrib#481]
```
ArgumentError: wrong number of arguments (given 1, expected 0; required keyword: field) (ArgumentError)
  from opentelemetry-instrumentation-graphql (0.26.0) lib/opentelemetry/instrumentation/graphql/tracers/graphql_trace.rb:141:in `platform_execute_field_key'
  from activesupport (7.0.4.3) lib/active_support/notifications.rb:206:in `instrument'
  from actionpack (7.0.4.3) lib/action_dispatch/middleware/stack.rb:60:in `call'
  from rack (2.2.7) lib/rack/deflater.rb:44:in `call'
  from actionpack (7.0.4.3) lib/action_dispatch/middleware/stack.rb:61:in `block in call'
```

Upgrading to 0.26 I get this error

**Comment by arielvalentin** [comment]
@dorianmariefr do you have any more details to share here?

What version of the GraphQL gem are you using? 

What version of Ruby are you running? 

cc: @swalkinshaw @rmosolgo

**Comment by arielvalentin** [comment]
@dorianmariefr we have released a bug fix for this. 

Please upgrade to graphql instrumentation 0.26.1 and report back your results here.

**Comment by arielvalentin** [comment]
@dorianmariefr any updates on this?

**Comment by dorianmariefr** [comment]
@arielvalentin yes, it was deployed last week and no issues, thx a lot
