### ISSUE TITLE
NoMethodError in PG adapter after upgrade

### ISSUE THREAD

**Issue by mockdeep** [open-telemetry/opentelemetry-ruby-contrib#486]
**Description of the bug**

When trying to upgrade `opentelemetry-instrumentation-pg` from 0.24.0 → 0.25.0 we start seeing an error coming from our tests. It tracks back to [this line](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/cfec2a5389a9abb331d8db83b44031f07e974804/instrumentation/pg/lib/opentelemetry/instrumentation/pg/patches/connection.rb#L111) which was introduced recently in [this commit](https://github.com/open-telemetry/opentelemetry-ruby-contrib/commit/b36902099ea90dc23d06bdc424a3fd6d08d5f9d7)

**Share details about your runtime**

Operating system details: Linux, Ubuntu 20.04 LTS
RUBY_ENGINE: "ruby"
RUBY_VERSION: "3.2.2"
RUBY_DESCRIPTION: "ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]"

**Share a simplified reproduction if possible**

Not sure if it's a repro, but here is the code that triggers the error:

```rb
RSpec.configure do |config|
  config.around(type: ->(type) { type != :feature }) do |example|
    Timecop.scale(10) { example.run }
  end
end
```

And here is the stack trace:

```
     NoMethodError:
       undefined method `-' for nil:NilClass
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/opentelemetry-instrumentation-pg-0.25.0/lib/opentelemetry/instrumentation/pg/patches/connection.rb:111:in `obfuscate_sql'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/opentelemetry-instrumentation-pg-0.25.0/lib/opentelemetry/instrumentation/pg/patches/connection.rb:72:in `span_attrs'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/opentelemetry-instrumentation-pg-0.25.0/lib/opentelemetry/instrumentation/pg/patches/connection.rb:18:in `block (2 levels) in <module:Connection>'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.0.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:48:in `block (2 levels) in execute'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.5/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.5/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.0.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:47:in `block in execute'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.5/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.5/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.5/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.5/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.0.5/lib/active_record/connection_adapters/abstract_adapter.rb:769:in `block in log'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.5/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.0.5/lib/active_record/connection_adapters/abstract_adapter.rb:760:in `log'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.0.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:46:in `execute'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.0.5/lib/active_record/connection_adapters/postgresql/referential_integrity.rb:12:in `block in disable_referential_integrity'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.0.5/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.5/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.5/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.5/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.5/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.0.5/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.0.5/lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.0.5/lib/active_record/connection_adapters/postgresql/referential_integrity.rb:11:in `disable_referential_integrity'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.0.5/lib/active_record/connection_adapters/abstract/database_statements.rb:407:in `block in insert_fixtures_set'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.0.5/lib/active_record/connection_adapters/abstract/database_statements.rb:531:in `with_multi_statements'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.0.5/lib/active_record/connection_adapters/abstract/database_statements.rb:406:in `insert_fixtures_set'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.0.5/lib/active_record/fixtures.rb:630:in `block in insert'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.0.5/lib/active_record/fixtures.rb:621:in `each'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.0.5/lib/active_record/fixtures.rb:621:in `insert'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.0.5/lib/active_record/fixtures.rb:607:in `read_and_insert'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.0.5/lib/active_record/fixtures.rb:567:in `create_fixtures'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.0.5/lib/active_record/test_fixtures.rb:275:in `load_fixtures'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.0.5/lib/active_record/test_fixtures.rb:125:in `setup_fixtures'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.0.5/lib/active_record/test_fixtures.rb:10:in `before_setup'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.0.5/lib/active_job/test_helper.rb:48:in `before_setup'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-rails-6.0.2/lib/rspec/rails/adapters.rb:74:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:390:in `execute_with'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in `call'
     # ./spec/rails_helper.rb:231:in `block (3 levels) in <top (required)>'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/timecop-0.9.6/lib/timecop/timecop.rb:201:in `travel'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/timecop-0.9.6/lib/timecop/timecop.rb:131:in `send_travel'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/timecop-0.9.6/lib/timecop/timecop.rb:75:in `scale'
     # ./spec/rails_helper.rb:231:in `block (2 levels) in <top (required)>'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:390:in `execute_with'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in `call'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:486:in `run'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:259:in `run'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:646:in `block in run_examples'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:642:in `map'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:642:in `run_examples'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:607:in `run'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:121:in `map'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration.rb:2070:in `with_suite_hooks'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/reporter.rb:74:in `report'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:115:in `run_specs'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:89:in `run'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:71:in `run'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:45:in `invoke'
     # /home/fletch/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/exe/rspec:4:in `<top (required)>'
     # /home/fletch/.asdf/installs/ruby/3.2.2/bin/rspec:25:in `load'
     # /home/fletch/.asdf/installs/ruby/3.2.2/bin/rspec:25:in `<main>'
     # /home/fletch/.asdf/installs/ruby/3.2.2/bin/ruby_executable_hooks:22:in `eval'
     # /home/fletch/.asdf/installs/ruby/3.2.2/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by arielvalentin** [comment]
thanks for reporting this error. 

Do you have any details with the SQL statement that it failed on?

**Comment by arielvalentin** [comment]
cc: @reid-rigo

**Comment by mockdeep** [comment]
@arielvalentin based on the stack trace, it looks like it's trying to insert database fixtures. Here's the query that causes the error:

```
"ALTER TABLE \"answers\" DISABLE TRIGGER ALL;ALTER TABLE \"action_text_rich_texts\" DISABLE TRIGGER ALL;ALTER TABLE \"active_storage_variant_records\" DISABLE TRIGGER ALL;ALTER TABLE \"api_keys\" DISABLE TRIGGER ALL;ALTER TABLE \"approver_lists_recipients\" DISABLE TRIGGER ALL;ALTER TABLE \"approver_lists\" DISABLE TRIGGER ALL;ALTER TABLE \"attachments\" DISABLE TRIGGER ALL;ALTER TABLE \"campaign_events\" DISABLE TRIGGER ALL;ALTER TABLE \"campaigns_internal_tags\" DISABLE TRIGGER ALL;ALTER TABLE \"campaigns_test_recipients\" DISABLE TRIGGER ALL;ALTER TABLE \"ccs\" DISABLE TRIGGER ALL;ALTER TABLE \"data_source_permissions\" DISABLE TRIGGER ALL;ALTER TABLE \"data_source_records\" DISABLE TRIGGER ALL;ALTER TABLE \"data_sources\" DISABLE TRIGGER ALL;ALTER TABLE \"database_locks\" DISABLE TRIGGER ALL;ALTER TABLE \"email_events\" DISABLE TRIGGER ALL;ALTER TABLE \"events\" DISABLE TRIGGER ALL;ALTER TABLE \"features\" DISABLE TRIGGER ALL;ALTER TABLE \"dropdowns\" DISABLE TRIGGER ALL;ALTER TABLE \"feedbacks\" DISABLE TRIGGER ALL;ALTER TABLE \"fields\" DISABLE TRIGGER ALL;ALTER TABLE \"form_access_groups\" DISABLE TRIGGER ALL;ALTER TABLE \"form_request_statuses\" DISABLE TRIGGER ALL;ALTER TABLE \"features_users\" DISABLE TRIGGER ALL;ALTER TABLE \"form_subsets\" DISABLE TRIGGER ALL;ALTER TABLE \"forms\" DISABLE TRIGGER ALL;ALTER TABLE \"form_sets\" DISABLE TRIGGER ALL;ALTER TABLE \"form_requests\" DISABLE TRIGGER ALL;ALTER TABLE \"friendly_id_slugs\" DISABLE TRIGGER ALL;ALTER TABLE \"internal_tags\" DISABLE TRIGGER ALL;ALTER TABLE \"pages\" DISABLE TRIGGER ALL;ALTER TABLE \"groups\" DISABLE TRIGGER ALL;ALTER TABLE \"job_results\" DISABLE TRIGGER ALL;ALTER TABLE \"organizations\" DISABLE TRIGGER ALL;ALTER TABLE \"pg_search_documents\" DISABLE TRIGGER ALL;ALTER TABLE \"recipients\" DISABLE TRIGGER ALL;ALTER TABLE \"recipients_steps\" DISABLE TRIGGER ALL;ALTER TABLE \"questions\" DISABLE TRIGGER ALL;ALTER TABLE \"recipients_subjects\" DISABLE TRIGGER ALL;ALTER TABLE \"roles\" DISABLE TRIGGER ALL;ALTER TABLE \"session_storages\" DISABLE TRIGGER ALL;ALTER TABLE \"signatures\" DISABLE TRIGGER ALL;ALTER TABLE \"stars\" DISABLE TRIGGER ALL;ALTER TABLE \"subjects\" DISABLE TRIGGER ALL;ALTER TABLE \"subject_versions\" DISABLE TRIGGER ALL;ALTER TABLE \"sessions\" DISABLE TRIGGER ALL;ALTER TABLE \"vals\" DISABLE TRIGGER ALL;ALTER TABLE \"campaigns\" DISABLE TRIGGER ALL;ALTER TABLE \"versions\" DISABLE TRIGGER ALL;ALTER TABLE \"active_storage_blobs\" DISABLE TRIGGER ALL;ALTER TABLE \"active_storage_attachments\" DISABLE TRIGGER ALL;ALTER TABLE \"steps\" DISABLE TRIGGER ALL;ALTER TABLE \"users\" DISABLE TRIGGER ALL;ALTER TABLE \"docs\" DISABLE TRIGGER ALL;ALTER TABLE \"emails\" DISABLE TRIGGER ALL;ALTER TABLE \"dropdown_options\" DISABLE TRIGGER ALL;ALTER TABLE \"features_organizations\" DISABLE TRIGGER ALL;ALTER TABLE \"form_set_actions\" DISABLE TRIGGER ALL;ALTER TABLE \"roles_users\" DISABLE TRIGGER ALL;ALTER TABLE \"user_events\" DISABLE TRIGGER ALL;ALTER TABLE \"schema_migrations\" DISABLE TRIGGER ALL;ALTER TABLE \"ar_internal_metadata\" DISABLE TRIGGER ALL"
```

And if I capture the errors, then after that I see this one triggers it, too:

```
"ALTER TABLE \"answers\" ENABLE TRIGGER ALL;ALTER TABLE \"action_text_rich_texts\" ENABLE TRIGGER ALL;ALTER TABLE \"active_storage_variant_records\" ENABLE TRIGGER ALL;ALTER TABLE \"api_keys\" ENABLE TRIGGER ALL;ALTER TABLE \"approver_lists_recipients\" ENABLE TRIGGER ALL;ALTER TABLE \"approver_lists\" ENABLE TRIGGER ALL;ALTER TABLE \"attachments\" ENABLE TRIGGER ALL;ALTER TABLE \"campaign_events\" ENABLE TRIGGER ALL;ALTER TABLE \"campaigns_internal_tags\" ENABLE TRIGGER ALL;ALTER TABLE \"campaigns_test_recipients\" ENABLE TRIGGER ALL;ALTER TABLE \"ccs\" ENABLE TRIGGER ALL;ALTER TABLE \"data_source_permissions\" ENABLE TRIGGER ALL;ALTER TABLE \"data_source_records\" ENABLE TRIGGER ALL;ALTER TABLE \"data_sources\" ENABLE TRIGGER ALL;ALTER TABLE \"database_locks\" ENABLE TRIGGER ALL;ALTER TABLE \"email_events\" ENABLE TRIGGER ALL;ALTER TABLE \"events\" ENABLE TRIGGER ALL;ALTER TABLE \"features\" ENABLE TRIGGER ALL;ALTER TABLE \"dropdowns\" ENABLE TRIGGER ALL;ALTER TABLE \"feedbacks\" ENABLE TRIGGER ALL;ALTER TABLE \"fields\" ENABLE TRIGGER ALL;ALTER TABLE \"form_access_groups\" ENABLE TRIGGER ALL;ALTER TABLE \"form_request_statuses\" ENABLE TRIGGER ALL;ALTER TABLE \"features_users\" ENABLE TRIGGER ALL;ALTER TABLE \"form_subsets\" ENABLE TRIGGER ALL;ALTER TABLE \"forms\" ENABLE TRIGGER ALL;ALTER TABLE \"form_sets\" ENABLE TRIGGER ALL;ALTER TABLE \"form_requests\" ENABLE TRIGGER ALL;ALTER TABLE \"friendly_id_slugs\" ENABLE TRIGGER ALL;ALTER TABLE \"internal_tags\" ENABLE TRIGGER ALL;ALTER TABLE \"pages\" ENABLE TRIGGER ALL;ALTER TABLE \"groups\" ENABLE TRIGGER ALL;ALTER TABLE \"job_results\" ENABLE TRIGGER ALL;ALTER TABLE \"organizations\" ENABLE TRIGGER ALL;ALTER TABLE \"pg_search_documents\" ENABLE TRIGGER ALL;ALTER TABLE \"recipients\" ENABLE TRIGGER ALL;ALTER TABLE \"recipients_steps\" ENABLE TRIGGER ALL;ALTER TABLE \"questions\" ENABLE TRIGGER ALL;ALTER TABLE \"recipients_subjects\" ENABLE TRIGGER ALL;ALTER TABLE \"roles\" ENABLE TRIGGER ALL;ALTER TABLE \"session_storages\" ENABLE TRIGGER ALL;ALTER TABLE \"signatures\" ENABLE TRIGGER ALL;ALTER TABLE \"stars\" ENABLE TRIGGER ALL;ALTER TABLE \"subjects\" ENABLE TRIGGER ALL;ALTER TABLE \"subject_versions\" ENABLE TRIGGER ALL;ALTER TABLE \"sessions\" ENABLE TRIGGER ALL;ALTER TABLE \"vals\" ENABLE TRIGGER ALL;ALTER TABLE \"campaigns\" ENABLE TRIGGER ALL;ALTER TABLE \"versions\" ENABLE TRIGGER ALL;ALTER TABLE \"active_storage_blobs\" ENABLE TRIGGER ALL;ALTER TABLE \"active_storage_attachments\" ENABLE TRIGGER ALL;ALTER TABLE \"steps\" ENABLE TRIGGER ALL;ALTER TABLE \"users\" ENABLE TRIGGER ALL;ALTER TABLE \"docs\" ENABLE TRIGGER ALL;ALTER TABLE \"emails\" ENABLE TRIGGER ALL;ALTER TABLE \"dropdown_options\" ENABLE TRIGGER ALL;ALTER TABLE \"features_organizations\" ENABLE TRIGGER ALL;ALTER TABLE \"form_set_actions\" ENABLE TRIGGER ALL;ALTER TABLE \"roles_users\" ENABLE TRIGGER ALL;ALTER TABLE \"user_events\" ENABLE TRIGGER ALL;ALTER TABLE \"schema_migrations\" ENABLE TRIGGER ALL;ALTER TABLE \"ar_internal_metadata\" ENABLE TRIGGER ALL"
```

**Comment by arielvalentin** [comment]
Thanks. We'll use these to write some unit tests to cover these cases.

**Comment by arielvalentin** [comment]
@reid-rigo It looks like the issue is with any DDL statement. I was able to reproduce the problem with  this test:

```ruby
        it 'truncates DDL statements to the config limit' do
          sql = 'ALTER TABLE "answers" DISABLE TRIGGER ALL'
          obfuscated_sql = 'ALTER TABLE "answers" DISABLE TRIGGER ALL'  # not sure what this should be
          expect do
            client.exec(sql)
          end.must_raise PG::UndefinedTable

          _(span.attributes['db.statement']).must_equal obfuscated_sql
        end
```

```console
  2) Failure:
OpenTelemetry::Instrumentation::PG::Instrumentation::tracing::when db_statement is obfuscate::with obfuscation_limit#test_0002_truncates DDL statements to the config limit [/workspaces/opentelemetry-ruby-contrib/instrumentation/pg/test/opentelemetry/instrumentation/pg/instrumentation_test.rb:289]:
[PG::UndefinedTable] exception expected, not
Class: <NoMethodError>
Message: <"undefined method `-' for nil:NilClass\n\n              truncated_sql = sql[..sql.index(generated_postgres_regex) - 1]\n                                                                        ^">
---Backtrace---
/workspaces/opentelemetry-ruby-contrib/instrumentation/pg/lib/opentelemetry/instrumentation/pg/patches/connection.rb:111:in `obfuscate_sql'
/workspaces/opentelemetry-ruby-contrib/instrumentation/pg/lib/opentelemetry/instrumentation/pg/patches/connection.rb:72:in `span_attrs'
/workspaces/opentelemetry-ruby-contrib/instrumentation/pg/lib/opentelemetry/instrumentation/pg/patches/connection.rb:18:in `block (2 levels) in <module:Connection>'
/workspaces/opentelemetry-ruby-contrib/instrumentation/pg/test/opentelemetry/instrumentation/pg/instrumentation_test.rb:290:in `block (6 levels) in <top (required)>'
---------------
```

I did not notice this but it also looks like we do not have any error handling in the PG obfuscation block like with do with other drivers. 

https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/cfec2a5389a9abb331d8db83b44031f07e974804/instrumentation/pg/lib/opentelemetry/instrumentation/pg/patches/connection.rb#L107

https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/cfec2a5389a9abb331d8db83b44031f07e974804/instrumentation/trilogy/lib/opentelemetry/instrumentation/trilogy/patches/client.rb#L97

I will take a look at reverting tomorrow if we are unable to track this down. 

I suspect that the mysql2 and trilogy instrumentations also have the same problem.
