### ISSUE TITLE
uninitialized constant OpenTelemetry::Helpers (NameError)

### ISSUE THREAD

**Issue by vzamanillo** [open-telemetry/opentelemetry-ruby-contrib#858]
After latest release v0.57.0 I am getting this error, the trace

```
E, [2024-02-08T10:43:07.944472 #17398] ERROR -- : uninitialized constant OpenTelemetry::Helpers (NameError)
/var/www/xx/shared/bundle/ruby/3.2.2/gems/opentelemetry-instrumentation-pg-0.27.0/lib/opentelemetry/instrumentation/pg/patches/connection.rb:56:in `obfuscate_sql'
/var/www/xx/shared/bundle/ruby/3.2.2/gems/opentelemetry-instrumentation-pg-0.27.0/lib/opentelemetry/instrumentation/pg/patches/connection.rb:90:in `span_attrs'
/var/www/xx/shared/bundle/ruby/3.2.2/gems/opentelemetry-instrumentation-pg-0.27.0/lib/opentelemetry/instrumentation/pg/patches/connection.rb:18:in `block (2 levels) in <module:Connection>'
/var/www/xx/shared/bundle/ruby/3.2.2/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:49:in `block (2 levels) in execute'
/var/www/xx/shared/bundle/ruby/3.2.2/gems/activesupport-6.1.5.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/var/www/xx/shared/bundle/ruby/3.2.2/gems/activesupport-6.1.5.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/var/www/xx/shared/bundle/ruby/3.2.2/gems/activesupport-6.1.5.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/var/www/xx/shared/bundle/ruby/3.2.2/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:48:in `block in execute'
/var/www/xx/shared/bundle/ruby/3.2.2/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block (2 levels) in log'
/var/www/xx/shared/bundle/ruby/3.2.2/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/var/www/xx/shared/bundle/ruby/3.2.2/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/var/www/xx/shared/bundle/ruby/3.2.2/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/var/www/xx/shared/bundle/ruby/3.2.2/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/var/www/xx/shared/bundle/ruby/3.2.2/gems/activesupport-6.1.5.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/var/www/xx/shared/bundle/ruby/3.2.2/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract_adapter.rb:695:in `block in log'
/var/www/xx/shared/bundle/ruby/3.2.2/gems/activesupport-6.1.5.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/var/www/xx/shared/bundle/ruby/3.2.2/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'
/var/www/xx/shared/bundle/ruby/3.2.2/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:47:in `execute'
```
**Runtime details**

Operating system details: CentOS Linux release 7.9.2009 (Core)
Rails: 6.1.5.1
RUBY_ENGINE: "ruby"
RUBY_VERSION: "3.2.2"
RUBY_DESCRIPTION: "ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]"

**Gemfile**

```
gem 'opentelemetry-sdk'
gem 'opentelemetry-exporter-otlp'
gem 'opentelemetry-instrumentation-all'
```

**Bundle gems (after updating)**

```
opentelemetry-common-0.20.1
opentelemetry-api-1.2.4
opentelemetry-exporter-otlp-0.26.3
opentelemetry-instrumentation-rails-0.30.0
opentelemetry-instrumentation-sinatra-0.23.2
opentelemetry-instrumentation-grape-0.1.6
opentelemetry-instrumentation-action_pack-0.9.0
opentelemetry-instrumentation-action_view-0.7.0
opentelemetry-instrumentation-ruby_kafka-0.21.0
opentelemetry-instrumentation-restclient-0.22.3
opentelemetry-instrumentation-redis-0.25.3
opentelemetry-instrumentation-rdkafka-0.4.2
opentelemetry-instrumentation-rake-0.2.1
opentelemetry-instrumentation-racecar-0.3.0
opentelemetry-instrumentation-net_http-0.22.4
opentelemetry-instrumentation-mongo-0.22.2
opentelemetry-instrumentation-lmdb-0.22.1
opentelemetry-instrumentation-http_client-0.22.3
opentelemetry-instrumentation-koala-0.20.2
opentelemetry-instrumentation-http-0.23.2
opentelemetry-instrumentation-gruf-0.1.1
opentelemetry-instrumentation-graphql-0.27.0
opentelemetry-instrumentation-dalli-0.25.0
opentelemetry-instrumentation-ethon-0.21.3
opentelemetry-instrumentation-faraday-0.23.4
opentelemetry-instrumentation-excon-0.22.0
opentelemetry-instrumentation-delayed_job-0.22.1
opentelemetry-instrumentation-concurrent_ruby-0.21.2
opentelemetry-instrumentation-rack-0.24.0
opentelemetry-instrumentation-active_model_serializers-0.20.1
opentelemetry-instrumentation-active_job-0.7.1
opentelemetry-instrumentation-active_record-0.7.0
opentelemetry-instrumentation-aws_sdk-0.5.0
opentelemetry-sdk-1.4.0
opentelemetry-instrumentation-active_support-0.5.1
opentelemetry-instrumentation-base-0.22.3
opentelemetry-common-0.20.0
opentelemetry-semantic_conventions-1.10.0
opentelemetry-registry-0.3.0
opentelemetry-instrumentation-all-0.57.0
opentelemetry-instrumentation-trilogy-0.59.0
opentelemetry-instrumentation-mysql2-0.26.0
opentelemetry-instrumentation-pg-0.27.0
opentelemetry-instrumentation-que-0.8.0
opentelemetry-instrumentation-resque-0.5.1
opentelemetry-instrumentation-sidekiq-0.25.1
opentelemetry-helpers-sql-obfuscation-0.1.0
opentelemetry-instrumentation-bunny-0.21.2
opentelemetry-helpers-mysql-0.1.0
```

**Updated gems, causing the error**

```
opentelemetry-instrumentation-all-0.57.0
opentelemetry-instrumentation-trilogy-0.59.0
opentelemetry-instrumentation-mysql2-0.26.0
opentelemetry-instrumentation-pg-0.27.0
opentelemetry-instrumentation-que-0.8.0
opentelemetry-instrumentation-resque-0.5.1
opentelemetry-instrumentation-sidekiq-0.25.1
opentelemetry-helpers-sql-obfuscation-0.1.0
opentelemetry-instrumentation-bunny-0.21.2
opentelemetry-helpers-mysql-0.1.0
```

**initializers/opentelemetry.rb**

```
require 'opentelemetry/sdk'
require 'opentelemetry/instrumentation/all'

OpenTelemetry::SDK.configure(&:use_all) unless Rails.env.development?
```

**Active instrumentation (initialization deploy log)**

```
WARN -- : Instrumentation: OpenTelemetry::Instrumentation::Gruf failed to install
WARN -- : Instrumentation: OpenTelemetry::Instrumentation::Trilogy failed to install
INFO -- : Instrumentation: OpenTelemetry::Instrumentation::ActiveSupport was successfully installed with the following options {}
INFO -- : Instrumentation: OpenTelemetry::Instrumentation::Rack was successfully installed with the following options {:allowed_request_headers=>[], :allowed_response_headers=>[], :application=>nil, :record_frontend_span=>false, :untraced_endpoints=>[], :url_quantization=>nil, :untraced_requests=>nil, :response_propagators=>[], :use_rack_events=>true, :allowed_rack_request_headers=>{}, :allowed_rack_response_headers=>{}}
INFO -- : Instrumentation: OpenTelemetry::Instrumentation::ActionPack was successfully installed with the following options {}
INFO -- : Instrumentation: OpenTelemetry::Instrumentation::ActiveJob was successfully installed with the following options {:propagation_style=>:link, :force_flush=>false, :span_naming=>:queue}
INFO -- : Instrumentation: OpenTelemetry::Instrumentation::ActiveRecord was successfully installed with the following options {}
INFO -- : Instrumentation: OpenTelemetry::Instrumentation::ActionView was successfully installed with the following options {:disallowed_notification_payload_keys=>[], :notification_payload_transform=>nil}
INFO -- : Instrumentation: OpenTelemetry::Instrumentation::AwsSdk was successfully installed with the following options {:inject_messaging_context=>false, :suppress_internal_instrumentation=>false}
WARN -- : Instrumentation: OpenTelemetry::Instrumentation::Bunny failed to install
WARN -- : Instrumentation: OpenTelemetry::Instrumentation::LMDB failed to install
WARN -- : Instrumentation: OpenTelemetry::Instrumentation::HTTP failed to install
WARN -- : Instrumentation: OpenTelemetry::Instrumentation::Koala failed to install
WARN -- : Instrumentation: OpenTelemetry::Instrumentation::ActiveModelSerializers failed to install
INFO -- : Instrumentation: OpenTelemetry::Instrumentation::ConcurrentRuby was successfully installed with the following options {}
WARN -- : Instrumentation: OpenTelemetry::Instrumentation::Dalli failed to install
WARN -- : Instrumentation: OpenTelemetry::Instrumentation::DelayedJob failed to install
WARN -- : Instrumentation: OpenTelemetry::Instrumentation::Ethon failed to install
WARN -- : Instrumentation: OpenTelemetry::Instrumentation::Excon failed to install
INFO -- : Instrumentation: OpenTelemetry::Instrumentation::Faraday was successfully installed with the following options {:peer_service=>nil}
WARN -- : Instrumentation: OpenTelemetry::Instrumentation::Grape failed to install
WARN -- : Instrumentation: OpenTelemetry::Instrumentation::GraphQL failed to install
INFO -- : Instrumentation: OpenTelemetry::Instrumentation::HttpClient was successfully installed with the following options {}
WARN -- : Instrumentation: OpenTelemetry::Instrumentation::Mongo failed to install
WARN -- : Instrumentation: OpenTelemetry::Instrumentation::Mysql2 failed to install
INFO -- : Instrumentation: OpenTelemetry::Instrumentation::Net::HTTP was successfully installed with the following options {:untraced_hosts=>[]}
INFO -- : Instrumentation: OpenTelemetry::Instrumentation::PG was successfully installed with the following options {:peer_service=>nil, :db_statement=>:obfuscate, :obfuscation_limit=>2000}
WARN -- : Instrumentation: OpenTelemetry::Instrumentation::Que failed to install
WARN -- : Instrumentation: OpenTelemetry::Instrumentation::Racecar failed to install
INFO -- : Instrumentation: OpenTelemetry::Instrumentation::Rails was successfully installed with the following options {}
WARN -- : Instrumentation: OpenTelemetry::Instrumentation::Rake failed to install
WARN -- : Instrumentation: OpenTelemetry::Instrumentation::Rdkafka failed to install
INFO -- : Instrumentation: OpenTelemetry::Instrumentation::Redis was successfully installed with the following options {:peer_service=>nil, :trace_root_spans=>true, :db_statement=>:obfuscate}
WARN -- : Instrumentation: OpenTelemetry::Instrumentation::RestClient failed to install
WARN -- : Instrumentation: OpenTelemetry::Instrumentation::Resque failed to install
WARN -- : Instrumentation: OpenTelemetry::Instrumentation::RubyKafka failed to install
INFO -- : Instrumentation: OpenTelemetry::Instrumentation::Sidekiq was successfully installed with the following options {:span_naming=>:queue, :propagation_style=>:link, :trace_launcher_heartbeat=>false, :trace_poller_enqueue=>false, :trace_poller_wait=>false, :trace_processor_process_one=>false, :peer_service=>nil}
WARN -- : Instrumentation: OpenTelemetry::Instrumentation::Sinatra failed to install
```

**Comment by arielvalentin** [comment]
Cc: @kaylareopelle

**Comment by vzamanillo** [comment]
I think it is a missing require

`require 'opentelemetry-helpers-sql-obfuscation'`

**Comment by vzamanillo** [comment]
@scbjans

Thank you.
