### ISSUE TITLE
GraphQL 2.2.10 Errors

### ISSUE THREAD

**Issue by arielvalentin** [open-telemetry/opentelemetry-ruby-contrib#882]
https://github.com/open-telemetry/opentelemetry-ruby-contrib/actions/runs/7980847045/job/21791358675

```console
  1) Error:
  OpenTelemetry::Instrumentation::GraphQL::Tracers::GraphQLTrace::#platform_trace#test_0001_traces platform keys:
  ArgumentError: wrong number of arguments (given 6, expected 7)
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/graphql-2.2.10/lib/graphql/language/nodes.rb:316:in `from_a'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/graphql-c_parser-1.0.7/lib/graphql/c_parser.rb:96:in `c_parse'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/graphql-c_parser-1.0.7/lib/graphql/c_parser.rb:96:in `block in result'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/trace/tracer.rb:37:in `block in in_span'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/trace.rb:70:in `block in with_span'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/context.rb:87:in `with_value'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/trace.rb:70:in `with_span'
      /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/trace/tracer.rb:37:in `in_span'
      lib/opentelemetry/instrumentation/graphql/tracers/graphql_trace.rb:71:in `parse'
```

cc: @rmosolgo

**Comment by rmosolgo** [comment]
Woah! My bad... I just released a parser "fix" but must have broken something 👀

**Comment by rmosolgo** [comment]
I changed this method signature in GraphQL-Ruby v2.2.10 but forgot that it requires a new release of graphql-c_parser, too. I just released graphql-c_parser 1.0.8 which should fix this. Please give it a try!

**Comment by arielvalentin** [comment]
Thanks for the fast turnaround! I'm restarting the jobs now

**Comment by arielvalentin** [comment]
Thanks for the quick response! Builds are passing now
